In [103]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sys
import math
from numpy import sqrt 
from math import cos

#   a) get the sample of normally distributed numbers, dimensions 2, the box-muller transform
array_Z = np.zeros(2000)
for i in range(0, 2000):         # sample of distribution
    m = 0
    sigma = 1
    c = 2 * math.pi
    alpha_1 = np.random.rand()   # равномерное распределение в интервале 0, 1
    alpha_2 = np.random.rand()
    r = sqrt(-2 * math.log(alpha_1))
    feta = c  * alpha_2
    Z = r * cos(feta)
    Z = m + sigma * Z
    array_Z[i] = Z
#plt.hist(array_Z)
array_Z = np.reshape(array_Z, (2, 1000))

#print(array_Z)
print(array_Z.shape)

#n = 3
#m = 1000000
#Z = np.round(np.random.normal(0, 1, [n,m]))
#print(Z)

# C.T * Z - this is the answer
#Sigma = [[1.0, 0.5, 0.5], [0.5, 2.0, 0.3], [0.5, 0.3, 1.5]]
#Sigma = np.array(Sigma)
#print(Sigma.reshape((3, 3)))

Sigma = [[1.0, 0.], [0., 1.0]]    # sigma for Cholesky Decomposition
Sigma = np.array(Sigma)

print(Sigma.reshape((2, 2)))

C = np.linalg.cholesky(Sigma)
C = np.transpose(C)
#C.shape
#Z.shape
X = np.dot(C, array_Z)
print(X)
#X = np.transpose(X)
#print(np.cov(X))

X.shape

#  b) Estimate the parameters
X = np.reshape(X, (1, 2000))
print(np.mean(X))
print(np.std(X))

(2, 1000)
[[1. 0.]
 [0. 1.]]
[[-0.63581886  0.77638893 -0.48046203 ...  0.0213799  -0.52555163
   0.65745071]
 [ 0.27667267 -1.86329062  1.40584511 ...  0.77809984  1.7240226
  -0.51957254]]
0.02206753303365765
0.9997948931775277


In [105]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sys
import math
from numpy import sqrt 
from math import cos

#   a) get the sample of normally distributed numbers, dimensions 5, the box-muller transform
array_Z = np.zeros(5000)
for i in range(0, 5000):         # sample of distribution
    m = 0
    sigma = 1
    c = 2 * math.pi
    alpha_1 = np.random.rand()   # равномерное распределение в интервале 0, 1
    alpha_2 = np.random.rand()
    r = sqrt(-2 * math.log(alpha_1))
    feta = c  * alpha_2
    Z = r * cos(feta)
    Z = m + sigma * Z
    array_Z[i] = Z
#plt.hist(array_Z)
array_Z = np.reshape(array_Z, (5, 1000))

#print(array_Z)
print(array_Z.shape)

#n = 3
#m = 1000000
#Z = np.round(np.random.normal(0, 1, [n,m]))
#print(Z)

# C.T * Z - this is the answer
#Sigma = [[1.0, 0.5, 0.5], [0.5, 2.0, 0.3], [0.5, 0.3, 1.5]]
#Sigma = np.array(Sigma)
#print(Sigma.reshape((3, 3)))

Sigma = [[1.0, 0., 0., 0., 0.], [0., 1.0, 0., 0., 0.], [0., 0., 1.0, 0., 0.], [0., 0., 0., 1.0, 0.], [0., 0, 0., 0., 1.0]]    # sigma for Cholesky Decomposition
Sigma = np.array(Sigma)

print(Sigma.reshape((5, 5)))

C = np.linalg.cholesky(Sigma)
C = np.transpose(C)
#C.shape
#Z.shape
X = np.dot(C, array_Z)
print(X)
#X = np.transpose(X)
#print(np.cov(X))

X.shape

#  b) Estimate the parameters
X = np.reshape(X, (1, 5000))
print(np.mean(X))
print(np.std(X))

(5, 1000)
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[-0.20850467  2.11985266  0.53538254 ... -1.46085817  0.58025156
  -1.47752174]
 [ 0.92994083  0.09565314  1.11687514 ...  0.10839101 -0.82687553
   0.92256337]
 [ 2.81116614  1.21416057  0.66814925 ... -0.70348827 -0.19157181
  -0.64906868]
 [-0.63638756  1.9130507   0.91200927 ... -1.2028927  -0.00293274
   0.22079478]
 [ 0.21614958 -0.20816831  1.80295071 ... -0.04974891 -1.65262755
   0.318802  ]]
0.02169321126547765
1.0066885942913881


In [106]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sys
import math
from numpy import sqrt 
from math import cos

#   a) get the sample of normally distributed numbers, dimensions 10, the box-muller transform
array_Z = np.zeros(10000)
for i in range(0, 10000):         # sample of distribution
    m = 0
    sigma = 1
    c = 2 * math.pi
    alpha_1 = np.random.rand()   # равномерное распределение в интервале 0, 1
    alpha_2 = np.random.rand()
    r = sqrt(-2 * math.log(alpha_1))
    feta = c  * alpha_2
    Z = r * cos(feta)
    Z = m + sigma * Z
    array_Z[i] = Z
#plt.hist(array_Z)
array_Z = np.reshape(array_Z, (10, 1000))

#print(array_Z)
print(array_Z.shape)

#n = 3
#m = 1000000
#Z = np.round(np.random.normal(0, 1, [n,m]))
#print(Z)

# C.T * Z - this is the answer
#Sigma = [[1.0, 0.5, 0.5], [0.5, 2.0, 0.3], [0.5, 0.3, 1.5]]
#Sigma = np.array(Sigma)
#print(Sigma.reshape((3, 3)))

Sigma = [[1, 0, 0, 0, 0,0, 0, 0, 0, 0], [0, 1, 0, 0, 0,0, 0, 0, 0, 0], [0, 0, 1, 0, 0,0, 0, 0, 0, 0], [0, 0, 0, 1, 0,0, 0, 0, 0, 0], [0, 0, 0, 0, 1,0, 0, 0, 0, 0],[0, 0, 0, 0, 0,1, 0, 0, 0, 0], [0, 0, 0, 0, 0,0, 1, 0, 0, 0], [0, 0, 0, 0, 0,0, 0, 1, 0, 0], [0, 0, 0, 0, 0,0, 0, 0, 1, 0], [0, 0, 0, 0, 0,0, 0, 0, 0, 1]]    # sigma for Cholesky Decomposition
Sigma = np.array(Sigma)

print(Sigma.reshape((10, 10)))

C = np.linalg.cholesky(Sigma)
C = np.transpose(C)
#C.shape
#Z.shape
X = np.dot(C, array_Z)
print(X)
#X = np.transpose(X)
#print(np.cov(X))

X.shape

#  b) Estimate the parameters
X = np.reshape(X, (1, 10000))
print(np.mean(X))
print(np.std(X))

(10, 1000)
[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]
[[ 0.10897678 -0.15742986 -0.00776364 ...  0.5041712   0.26142917
   1.53853777]
 [-0.20247228  0.43693306 -0.87218724 ... -1.13116705  0.72167754
   0.868176  ]
 [ 0.32001147 -0.20193375  1.30723813 ...  1.01565057 -1.41103345
  -1.48784965]
 ...
 [-0.60128486  0.14409482  0.02569439 ... -0.58858079 -0.10475537
  -1.45610011]
 [-0.04592222 -1.84549542  0.88134834 ... -0.05750943  0.96245312
   0.35047288]
 [-1.22525283 -1.82266005  0.37707611 ... -1.32112517 -1.82225848
  -0.09829045]]
0.0009527734389400259
1.0078349916616627


In [109]:
# C, D
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sys
import math
from numpy import sqrt 
from math import cos

#   a) get the sample of normally distributed numbers, dimensions 2, the box-muller transform
array_Z = np.zeros(2000)
for i in range(0, 2000):         # sample of distribution
    m = -2
    sigma = 1
    c = 2 * math.pi
    alpha_1 = np.random.rand()   # равномерное распределение в интервале 0, 1
    alpha_2 = np.random.rand()
    r = sqrt(-2 * math.log(alpha_1))
    feta = c  * alpha_2
    Z = r * cos(feta)
    Z = m + sigma * Z
    array_Z[i] = Z
#plt.hist(array_Z)
array_Z = np.reshape(array_Z, (2, 1000))

#print(array_Z)
print(array_Z.shape)

#n = 3
#m = 1000000
#Z = np.round(np.random.normal(0, 1, [n,m]))
#print(Z)

# C.T * Z - this is the answer
#Sigma = [[1.0, 0.5, 0.5], [0.5, 2.0, 0.3], [0.5, 0.3, 1.5]]
#Sigma = np.array(Sigma)
#print(Sigma.reshape((3, 3)))

Sigma = [[0.5, 2], [0.3, 0.7]]    # sigma for Cholesky Decomposition
Sigma = np.array(Sigma)

print(Sigma.reshape((2, 2)))

C = np.linalg.cholesky(Sigma)
C = np.transpose(C)
#C.shape
#Z.shape
X = np.dot(C, array_Z)
print(X)
#X = np.transpose(X)
#print(np.cov(X))

X.shape

#  b) Estimate the parameters
X = np.reshape(X, (1, 2000))
print(np.mean(X))
print(np.std(X))


(2, 1000)
[[0.5 2. ]
 [0.3 0.7]]
[[-3.31118102 -1.7702838  -2.91489826 ... -3.20513813 -1.4899107
  -2.74354806]
 [-1.62780409 -1.05336366 -1.3924998  ... -2.7900678  -0.50192092
  -2.29493171]]
-1.8827901479364284
0.8686751875868387
