In [1]:
import numpy as np

# Set the dimensions
dims = [2, 5, 10]

# Generate random vectors for each dimension
for dim in dims:
    mean = np.zeros(dim)
    cov = np.eye(dim)
    samples = np.random.multivariate_normal(mean, cov, size=10)
    print(f"Random vectors of dimension {dim}:\n{samples}\n")

Random vectors of dimension 2:
[[ 0.48375887  0.19286017]
 [-0.06019682  1.704668  ]
 [ 0.46175081  0.54611242]
 [-0.15307238  0.52734102]
 [-0.90827996  0.54120691]
 [-0.46832169 -0.36069761]
 [ 0.06666389 -1.04998137]
 [ 0.07705843  0.21621193]
 [ 1.01800595  0.56919401]
 [-0.70284126  0.01332748]]

Random vectors of dimension 5:
[[ 0.57681258  0.32623828  1.04332063  1.60174732  0.47738037]
 [-0.76229867 -0.72199735 -1.11027119 -1.77277453  0.99980667]
 [-2.03139414 -0.49794855  1.29693647 -0.10703579  1.18831141]
 [ 0.10474278  0.21037423  0.03983577 -0.3808595  -1.03448881]
 [-1.04893317 -0.22914066  0.22923184  1.98929866  0.7355375 ]
 [-0.33012637  0.95820328  1.14505466 -0.04134122 -0.52253518]
 [ 1.76676034 -0.50485106  1.23714252  0.29956394  0.33595366]
 [ 0.46624423 -1.15309127 -0.13248757 -0.7945001  -0.65016607]
 [-1.31054815 -1.53684245 -0.91835822 -0.6583997   0.93195162]
 [ 1.25278624  0.74609521 -0.80097331  1.14376367  0.11606556]]

Random vectors of dimension 10:
[[

In [2]:
# Set the dimension and sample size
dim = 5
size = 100

# Generate a sample set of random vectors
mean = np.zeros(dim)
cov = np.eye(dim)
samples = np.random.multivariate_normal(mean, cov, size=size)

# Estimate the mean and covariance matrix of the underlying distribution
sample_mean = np.mean(samples, axis=0)
sample_cov = np.cov(samples.T)

print(f"Sample mean:\n{sample_mean}\n")
print(f"Sample covariance matrix:\n{sample_cov}\n")

Sample mean:
[ 0.01713729  0.06984888 -0.00047806  0.09629751  0.06229759]

Sample covariance matrix:
[[ 0.90928467 -0.09553534 -0.14809783 -0.10272637  0.01952593]
 [-0.09553534  0.83603128  0.04362074 -0.07072168 -0.13041925]
 [-0.14809783  0.04362074  0.88476586  0.03470913 -0.06666867]
 [-0.10272637 -0.07072168  0.03470913  1.18552735 -0.1315843 ]
 [ 0.01952593 -0.13041925 -0.06666867 -0.1315843   1.01261007]]



In [3]:
import numpy as np

# Set the dimension, mean vector, and covariance matrix
dim = 3
mean = [1, 2, 3]
cov = [[2, 1, 0], [1, 2, 1], [0, 1, 2]]

# Generate a sample set of random vectors
samples = np.random.multivariate_normal(mean, cov, size=10)

print(f"Random vectors with mean vector {mean} and covariance matrix:\n{cov}\n")
print(f"{samples}\n")


Random vectors with mean vector [1, 2, 3] and covariance matrix:
[[2, 1, 0], [1, 2, 1], [0, 1, 2]]

[[ 5.07171532  3.63681334  0.87509785]
 [ 0.4267589   2.23133305  3.9387654 ]
 [-0.6744814  -0.03312096  4.02261598]
 [ 1.36203006  2.80130789  2.42271173]
 [ 0.04477937  2.4110378   3.16808557]
 [ 0.21545939  1.50806649  3.26506816]
 [ 3.07910254  3.26118868  2.26527829]
 [ 1.7080278   0.73295556  0.91051905]
 [ 0.22354359  1.92563869  3.2053251 ]
 [ 0.81623839  1.55614567  1.76224535]]

